### ISSUE TITLE
liveproxy port

### ISSUE THREAD

**Issue by maanich** [back-to/liveproxy#1]
howto change liveproxy port after install  where i find the config file

**Comment by back-to** [comment]
run it like `liveproxy --port PORT`

**Comment by maanich** [comment]
thanks what is concept behind live poxy as we can run same stream with streamlink how can we use it for geo restricted ip
i run a stream with live  proxy n found error in log but stream workig at the end.
liveproxy
[liveproxy-shared][info] LiveProxy is running as root! Be careful!
[liveproxy-main][info] For LiveProxy support visit https://github.com/back-to/liveproxy
[liveproxy-main][debug] OS:            Linux-3.13.0-149-generic-x86_64-with-Ubuntu-14.04-trusty
[liveproxy-main][debug] Python:        2.7.6
[liveproxy-main][debug] LiveProxy:     0.0.3
[liveproxy-main][debug] Streamlink:    0.14.0+12.g0cf6ce0
[liveproxy-main][debug] Requests(2.2.1), Websocket(0.48.0)
[liveproxy-main][info] Starting server: 127.0.0.1 on port 53422
[liveproxy-server][info] User-Agent: Xtream-Codes IPTV Panel Pro
[liveproxy-server][info] Client: ('127.0.0.1', 28855)
[liveproxy-server][info] Address: localhost
[liveproxy-server][info] Plugin path /root/.config/streamlink/plugins does not exist or is not a directory!
[liveproxy-server][info] Found matching plugin tvcatchup for URL https://tvcatchup.com/watch/itv
[liveproxy-server][info] Available streams: 550k (worst), 900k, 1200k (best)
[liveproxy-server][info] Opening stream: 1200k (hls)
[liveproxy-server][error] [Errno 104] Connection reset by peer
[liveproxy-server][info] Stream ended
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 28855)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
[liveproxy-server][info] User-Agent: xxxxxxxx
[liveproxy-server][info] Client: ('127.0.0.1', 28860)
[liveproxy-server][info] Address: localhost
[liveproxy-server][info] Plugin path /root/.config/streamlink/plugins does not exist or is not a directory!
[liveproxy-server][info] Found matching plugin tvcatchup for URL https://tvcatchup.com/watch/itv
[liveproxy-server][info] Available streams: 550k (worst), 900k, 1200k (best)
[liveproxy-server][info] Opening stream: 1200k (hls)


[liveproxy-server][info] Plugin path /root/.config/streamlink/plugins does not exist or is not a directory! what is that error n how to get this directory

**Comment by back-to** [comment]
> what is concept behind live poxy as we can run same stream with streamlink

LiveProxy is a local Proxyserver between Streamlink and an URL.

It is used for **local devices which can't run streamlink**

> how can we use it for geo restricted ip

https://liveproxy.github.io/url.html#options
with https://streamlink.github.io/cli.html#proxy-support

> i run a stream with live proxy n found error in log but stream workig at the end.

it is just a python2.7 error because you closed the stream
https://liveproxy.github.io/known_issues.html#errno-32

> Plugin path /root/.config/streamlink/plugins does not exist or is not a directory!
   what is that error n how to get this directory

it is for custom plugins https://streamlink.github.io/cli.html#sideloading-plugins
you don't need it

**Comment by maanich** [comment]
liveproxy --host 95.218.252.189 --port 54322
[liveproxy-shared][info] LiveProxy is running as root! Be careful!
[liveproxy-main][info] For LiveProxy support visit https://github.com/back-to/liveproxy
[liveproxy-main][debug] OS:            Linux-4.4.0-31-generic-x86_64-with-Ubuntu-14.04-trusty
[liveproxy-main][debug] Python:        2.7.6
[liveproxy-main][debug] LiveProxy:     0.0.3
[liveproxy-main][debug] Streamlink:    0.14.2
[liveproxy-main][debug] Requests(2.2.1), Websocket(0.48.0)
[liveproxy-main][info] Starting server: 95.218.252.189 on port 54322
Traceback (most recent call last):
  File "/usr/local/bin/liveproxy", line 11, in <module>
    load_entry_point('liveproxy==0.0.3', 'console_scripts', 'liveproxy')()
  File "build/bdist.linux-x86_64/egg/liveproxy/main.py", line 69, in main
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address

got this error when try to add host if run  liveproxy it run with localhost and default port but assigning wan it isnt work

**Comment by back-to** [comment]
you need to use `--host 0.0.0.0` this will allow other devices

**Comment by maanich** [comment]
thanks  alot mate.
 i m running liveproxy n streamlink on my local uk based ip
when i run itv stream on vlc it give me error might be a username pass authentication 
how to add username pass for itv plugin with liveproxy and where ti make config file for user and pass   regards.

[liveproxy-server][warning] Plugin path /root/.config/streamlink/plugins does not exist or is not a directory!
[liveproxy-server][info] Found matching plugin itvplayer for URL https://www.itv.com/hub/itv
[liveproxy-server][error] PluginError Unable to open URL: https://secure-mercury.itv.com/PlaylistService.svc?wsdl (503 Server Error: Service Unavailable for url: https://secure-mercury.itv.com/PlaylistService.svc?wsdl)
[liveproxy-server][info] User-Agent: VLC/3.0.3 LibVLC/3.0.3
[liveproxy-server][info] Client: ('86.3.77.209', 3816)
[liveproxy-server][info] Address: cpc124700-birk9-2-0-cust464.1-3.cable.virginm.net
[liveproxy-server][warning] Plugin path /root/.config/streamlink/plugins does not exist or is not a directory!
[liveproxy-server][info] Found matching plugin itvplayer for URL https://www.itv.com/hub/itv
[liveproxy-server][error] PluginError Unable to open URL: https://secure-mercury.itv.com/PlaylistService.svc?wsdl (503 Server Error: Service Unavailable for url: https://secure-mercury.itv.com/PlaylistService.svc?wsdl)

**Comment by maanich** [comment]
thanks alot mate.
i m running liveproxy n streamlink on my local uk based ip
when i run itv stream on vlc it give me error might be a username pass authentication
how to add username pass for itv plugin with liveproxy and where ti make config file for user and pass regards.

[liveproxy-server][warning] Plugin path /root/.config/streamlink/plugins does not exist or is not a directory!
[liveproxy-server][info] Found matching plugin itvplayer for URL https://www.itv.com/hub/itv
[liveproxy-server][error] PluginError Unable to open URL: https://secure-mercury.itv.com/PlaylistService.svc?wsdl (503 Server Error: Service Unavailable for url: https://secure-mercury.itv.com/PlaylistService.svc?wsdl)
[liveproxy-server][info] User-Agent: VLC/3.0.3 LibVLC/3.0.3
[liveproxy-server][info] Client: ('86cccccc209', 3816)
[liveproxy-server][info] Address: xxxxxx.xxxxxxx.net
[liveproxy-server][warning] Plugin path /root/.config/streamlink/plugins does not exist or is not a directory!
[liveproxy-server][info] Found matching plugin itvplayer for URL https://www.itv.com/hub/itv
[liveproxy-server][error] PluginError Unable to open URL: https://secure-mercury.itv.com/PlaylistService.svc?wsdl (503 Server Error: Service Unavailable for url: https://secure-mercury.itv.com/PlaylistService.svc?wsdl)

**Comment by maanich** [comment]
thanks alot it s fine  last question
how much bandwidth we need if i use liveproxy in my local pc to run atleast 10 streams live to my vps to avoid geo restriction.  will it need some bandwidth or its just to forward stream and has very less usage of bandwodth.
right now i hv an upload speed of 3 mb.

**Comment by back-to** [comment]
it would be the same as if you used streamlink with 10 streams

so it might be pretty high

**Comment by maanich** [comment]
[liveproxy-server][info] Plugin path /root/.config/streamlink/plugins does not exist or is not a directory!
[liveproxy-server][info] Found matching plugin itvplayer for URL https://www.itv.com/hub/citv
[liveproxy-server][info] Available streams: 660k_alt (worst), 660k, 880k_alt, 880k, 1320k_alt, 1320k, 1650k_alt, 1650k, 1980k_alt, 1980k (best)
[liveproxy-server][info] Opening stream: 1980k (hls)
[liveproxy-server][info] Detected remote disconnect
[liveproxy-server][info] Stream ended
----------------------------------------
Exception happened during processing of request from ('62.210.142.58', 29898)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
-------------------------------

**Comment by maanich** [comment]
i added three streams from itv     2 streams ok n third one gives this error 

[liveproxy-server][info] Plugin path /root/.config/streamlink/plugins does not exist or is not a directory!
[liveproxy-server][info] Found matching plugin itvplayer for URL https://www.itv.com/hub/citv
[liveproxy-server][info] Available streams: 660k_alt (worst), 660k, 880k_alt, 880k, 1320k_alt, 1320k, 1650k_alt, 1650k, 1980k_alt, 1980k (best)
[liveproxy-server][info] Opening stream: 1980k (hls)
[liveproxy-server][info] Detected remote disconnect
[liveproxy-server][info] Stream ended
Exception happened during processing of request from ('xxxxxxxxx', 29898)
Traceback (most recent call last):
File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
self.finish_request(request, client_address)
File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
self.RequestHandlerClass(request, client_address, self)
File "/usr/lib/python2.7/SocketServer.py", line 651, in init
self.finish()
File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
self.wfile.close()
File "/usr/lib/python2.7/socket.py", line 279, in close
self.flush()
File "/usr/lib/python2.7/socket.py", line 303, in flush
self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

**Comment by back-to** [comment]
https://liveproxy.github.io/known_issues.html#errno-32

> [liveproxy-server][info] Detected remote disconnect
[liveproxy-server][info] Stream ended

you closed the stream with your player

**Comment by maanich** [comment]
it automatically disconnectedcand connected aftet two streams might be the banfwidth issue as only 3 mb upload
