### ISSUE TITLE
[Question] There is a way to do some temp cache before streaming through the liveproxy ?

### ISSUE THREAD

**Issue by CyberPoison** [back-to/liveproxy#10]
Hi, @back-to there is some way to do a little of cache before streaming the content, i ask this because my tv get some freezes when i use liveproxy from twitch content, so i use a player that allow me to cache a bit before playing the live from twitch, so instead of using the cache i really would like to do cache from the rapberry pi to prevent freezes and doing it from my rapberry pi instead of my player, maybe a command from streamlink but i didn't find nothing.

Can you help me with this ?
I just need a little cache so maybe 10 - 20 seconds of caching the content to be ready for use at any moment, i have tested it and looks like the live proxy grab the m3u8 links great without issues, i just need some way to do caching of the content. 10-20 seconds will be good. 

Kind Regards

**Comment by back-to** [comment]
well, might be possible

but are you sure your rpi or tv can handle the bitrate of the stream
maybe just another quality such as **720p** would solve it.

> cache from the rapberry pi to prevent freezes

well this could result in the opposite with more data stored on the rpi

---

could you first try some **streamlink commands**

`--hls-live-edge 10`
https://streamlink.github.io/cli.html#cmdoption-hls-live-edge

`--ringbuffer-size 4M` or `--ringbuffer-size 32M`
https://streamlink.github.io/cli.html#cmdoption-ringbuffer-size

---

**or**

some **liveproxy** changes

change the pre buffer cache
https://github.com/back-to/liveproxy/blob/3dbcc8550b8aa108a5d84fff2f96b722feb9ab2a/liveproxy/server.py#L490

or

add two new lines there with
```py
                        import time
                        time.sleep(15)
```

**Comment by CyberPoison** [comment]
Looks like it fixed my issue so now i have my m3u like this :)

```
#EXTINF:-1 tvg-name="[Twitch] DrDisrespect [EN]" tvg-logo="https://static-cdn.jtvnw.net/jtv_user_pictures/72a69c72-14b9-4be8-b8cb-802bc3e5f8ed-profile_image-70x70.png"
streamlink --ringbuffer-size 64M --hls-live-edge 30 --hls-segment-threads 3 https://www.twitch.tv/drdisrespect best
```
and it fixed **maybe** my issue, now i have 20-25 seconds ready to be played, without buffering or laggs,

I will try with other twitch channels to check if it works great but at normally everything is alright.

Just a question when liveproxy will be avalaible on docker ? 
any idea ? 

Kind Regards

**Comment by CyberPoison** [comment]
As i have tested the 
```
streamlink --ringbuffer-size 64M --hls-live-edge 30
```
Command works only for one connection not for multiple connections, like mobile and tv for e.g.
so i will pass to **try nº2 ** 
but i don't know how can i use it can you tell me how can i use **try nº2 ** on liveproxy already installed ?

**Comment by back-to** [comment]
> --hls-segment-threads 3

try it without this

> Just a question when liveproxy will be avalaible on docker ?

no

> Command works only for one connection not for multiple connections, like mobile and tv for e.g.

so it lags again?

> but i don't know how can i use it can you tell me how can i use **try nº2 ** on liveproxy already installed ?

you have to change the file `liveproxy/server.py` locally

**Comment by CyberPoison** [comment]
> 
> > Command works only for one connection not for multiple connections, like mobile and tv for e.g.
> 
> so it lags again?
> 

Yes if I'm watching the same url over my móbile on VLC and my friends/family on my tv it lags me on the mobile because I don't have cache only the first connected have cache the seconds looks like don't have.
