### ISSUE TITLE
Kodi support, mpv for m3u8 link changes resolution?

### ISSUE THREAD

**Issue by siliconhippy** [back-to/liveproxy#24]
Hey back-to !

Stumbled here googling...

1. My main concern is converting video sources, e.g. youtube, to run on VLC and Kodi via .m3u/8 conversion or other. And then avoiding link changes if possible !

I read on Reddit that streamlink set to mpv will handle any m3u8 link changes on the fly:
https://www.reddit.com/r/commandline/comments/g4y0uv/create_m3u_from_permanent_youtube_streaming_link/fo0yprf/

2. So how can I set this up using liveproxy on Kodi 18/19, and for VLC on Windows PC?
3. Is there a way to reduce (youtube/ other site?) streaming delays?

Cheers,
Shippy.

**Comment by back-to** [comment]
> My main concern is converting video sources, e.g. youtube, to run on VLC and Kodi via .m3u/8 conversion or other. And then avoiding link changes if possible !

It is possible, but you will need a local server or pc where you can run liveproxy
https://github.com/back-to/liveproxy#installation

Liveproxy with Streamlink Youtube Example

https://github.com/back-to/liveproxy#streamlink

> So how can I set this up using liveproxy on Kodi 18/19, and for VLC on Windows PC?

Install it with Python and use it.

https://github.com/back-to/liveproxy#readme

> Is there a way to reduce (youtube/ other site?) streaming delays?

maybe, but thats on Streamlinks end not Liveproxy

**Comment by siliconhippy** [comment]
Hi again back-to !

 Very nice work and just in time v2.0.0 upgrade for me.

Yes I did read the guide page...

1. So I am assuming this can be installed in Linux via ssh CLI  on a tv box running Kodi JeOS like Libreelec or Coreelec.

2. Can liveproxy + YouTube-dl + Streamlink also be installed remotely in VPS/Cloud with 127.0.0.1 in https string replaced by VPS public IP?

The idea here is so users only need to install VLC ( usually installed by default) or mpv on their home PCs, and then just input example.m3u.new in the VLC ?

Setting up liveproxy could be complicated for the average user.

3. Can both VLC and mpv players be used with liveproxy to take care of .m3u8 link changes automatically in real time?

Cheers 😸,
Shippy.

**Comment by back-to** [comment]
> So I am assuming this can be installed in Linux via ssh CLI on a tv box running Kodi JeOS like Libreelec or Coreelec.

You need Python and Pip, should also work on Windows.
Also Streamlink or Youtube-DL

> Can liveproxy + YouTube-dl + Streamlink also be installed remotely in VPS/Cloud with 127.0.0.1 in https string replaced by VPS public IP?

yes `liveproxy --host 0.0.0.0` 
but **user could abuse your server,** Liveproxy is meant for local or private use not public servers.

> Can both VLC and mpv players be used with liveproxy to take care of .m3u8 link changes automatically in real time?

sure, just try it and see if it works for you.

you might want to test Streamlink itself first, before using Liveproxy

https://streamlink.github.io/cli.html

**Comment by siliconhippy** [comment]
Thanks for all this. 
Will try out. Yes I read the Streamlink doc.

I guess I will need something like a private IPTV Panel software to put in usr/ pwd ( fake MAC address) + valid time period creds in m3u links URL to avoid user abuse. I am trying to set things up for a group of friends and community, who just want AIO free Plex, Tubi , Pluto, YouTube channels/ playlists. 

But external actors can always barge in... 👺

Any suggestions for such cred input package?
I am not a dev, a Linux noob. So can monkey type at least ! 🤣

Cheers 😸,
Shippy.
