### ISSUE TITLE
Redirect Streamlink to VLC for Android on local network

### ISSUE THREAD

**Issue by ownchoice** [back-to/liveproxy#25]
Hello, I'm trying to redirect the stream from Streamlink on my PC (Windows/Linux, dual boot) to watch it on VLC on my Android phone.

My first problem is that it seems like liveproxy's stream it's not accessible from my local network.

My second problem is that VLC on Windows can't play liveproxy's stream, so I'm curious if VLC for Android can.
```
[server.4dac8][INFO] User-Agent: VLC/3.0.16 LibVLC/3.0.16
[server.4dac8][INFO] Client: ('127.0.0.1', 1658)
[server.4dac8][INFO] Address: 127.0.0.1
[server.4dac8][ERROR] Video-Software is not supported.
```

I use Streamlink with VLC on my PC, and I just want to watch the stream from my phone without needing to install Termux or something similar.

It's seems like an easy task, but I can't get it to work.

Thanks.

**Comment by back-to** [comment]
@ownchoice 

> My first problem is that it seems like liveproxy's stream it's not accessible from my local network.

use `liveproxy --host 0.0.0.0`

> My second problem is that VLC on Windows can't play liveproxy's stream, so I'm curious if VLC for Android can.
[server.4dac8][ERROR] Video-Software is not supported.

Streamlink path is not detected
could you run `liveproxy --loglevel DEBUG` and share the log output

> I use Streamlink with VLC on my PC, and I just want to watch the stream from my phone without needing to install Termux or something similar.

depends on your need you could also use a Streamlink instead of Liveproxy

`streamlink --player-external-http` https://streamlink.github.io/cli.html#cmdoption-player-external-http

**Comment by back-to** [comment]
>  my PC (Windows

just looked at it, it can't work on Windows

`from select import select` does not work with Windows, which is used in Liveproxy

https://github.com/back-to/liveproxy/blob/2.0.0/liveproxy/server.py#L116

https://docs.python.org/3.7/library/select.html#select.select

Liveproxy will only work with **Linux**, not Windows

Ref https://github.com/back-to/liveproxy/commit/10cbdc49cff5e65dfd9e8bc4f0f3581d27480591

**Comment by ownchoice** [comment]
Thanks a lot!

For some reason I just ignored the `--player-external-http` option when reading Streamlink's docs, but that is exactly what I was looking for.

Cheers.
