### ISSUE TITLE
.m3u8.new as playlist input for WordPress embedded video players

### ISSUE THREAD

**Issue by siliconhippy** [back-to/liveproxy#26]
Hi again,

This time I wonder about various WordPress embedded video players that all use hls.js as backend for their m3u8 playlists URLs:
https://wpneon.com/best-wordpress-video-player-plugins/
For example, #5,7,9, and also Presto player. 
Many players can only stream YouTube in iframes, and not as part of mixed playlist.

I don't think we can use a playlist as input that has streamlink or pipe commands to convert the YouTube URLs etc.

1. So can we use liveproxy .m3u8.new output file as playlist for above video players ?

Of course you will have to install WordPress+ embedded player plugins and Streamlink + liveproxy on the Linux server.

2. Will streamlink then automatically return the HLS streams to the embedded video player and update the YouTube URL/m3u8 link changes periodically ( one hour)?

Cheers 😸,
Shippy.
----

**Comment by back-to** [comment]
You are asking question which are not related to LiveProxy,
just try it and see if it works or not.
