### ISSUE TITLE
Generating a new file

### ISSUE THREAD

**Issue by dct-infra** [back-to/liveproxy#28]
Hello,
First thank you for thisd piece of software, very helpful.

I'm having an issue while creating a new file using the command 
liveproxy --file filename.m3u

The new generated file contains the default URL http://127.0.0.1:53422/ while in my case liveproxy listens on an external interface:port so I have to modify the m3u manually each time. 
Any way to specify the URL within the command itself?

Thanks.

**Comment by back-to** [comment]
yes, you can change the host and the port

```
Server options:
  --host HOST         A fixed IP to use as a HOST. Can also be used for `--file` Default is 127.0.0.1
  --port PORT         A fixed PORT to use for the HOST. Can also be used for `--file` Default is 53422
```
