### ISSUE TITLE
[ERROR] Video-Software is not supported.

### ISSUE THREAD

**Issue by 94maldini** [back-to/liveproxy#29]
Hello,

I just tried this, but the error code appears Video-Software is not supported.

how to fix?

**Comment by back-to** [comment]
share some more information,
run Liveproxy with `--loglevel DEBUG`

**Comment by Nincodedo** [comment]
I have this same issue. Here is my log with debug enabled.

```
[server.c0907][INFO] Address: 127.0.0.1
[server.c0907][DEBUG] Video-Software: C:\Users\Mike\AppData\Roaming\Python\Python38\Scripts\streamlink.EXE
[server.c0907][ERROR] Video-Software is not supported.
```

**Comment by back-to** [comment]
@Nincodedo 

Windows is not supported
https://github.com/back-to/liveproxy/commit/10cbdc49cff5e65dfd9e8bc4f0f3581d27480591

**Comment by Nincodedo** [comment]
Ah, didn't see that in the README. Thank you for answering.
