### ISSUE TITLE
Liveproxy 1.0.0

### ISSUE THREAD

**Issue by thawtes** [back-to/liveproxy#30]
hello dear @back-to 

i use LiveProxy 1.0.0 on enigma2 system

What do you think could be the source of the following problem?

`Traceback (most recent call last):
  File "/usr/bin/liveproxy", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/liveproxy/main.py", line 117, in main
    httpd = ThreadedHTTPServer((HOST, PORT), HTTPRequest)
  File "/usr/lib/python2.7/SocketServer.py", line 420, in __init__
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
  File "/usr/lib/python2.7/SocketServer.py", line 434, in server_bind
  File "/usr/lib/python2.7/socket.py", line 228, in meth
socket.error: [Errno 125] Address already in use`

**Comment by back-to** [comment]
> [Errno 125] Address already in use

something is already running with same port, try to restart or a different port

**Comment by thawtes** [comment]
> something is already running with same port, try to restart or a different port

okay, I got it but only run liveproxy-server

**Comment by back-to** [comment]
try a different port `--port 33333`

**Comment by thawtes** [comment]
I think I need to update /etc/init.d/liveproxy-server

**Comment by thawtes** [comment]
why did you remove support for Python2x/Enigma2? (it was working very well)

**Comment by back-to** [comment]
> why did you remove support for Python2x/Enigma2?

Streamlink dropped Python2 support, so did I.
**It is just to old.**

There are other E2 Images which support Python3,
such as openATV 7.0 https://github.com/openatv/enigma2

**Comment by thawtes** [comment]
> > why did you remove support for Python2x/Enigma2?
> 
> Streamlink dropped Python2 support, so did I. **It is just to old.**
> 
> There are other E2 Images which support Python3, such as openATV 7.0 https://github.com/openatv/enigma2

ok i use now openatv 7.0

how to install latest liveproxy ?

you source copy to /usr/lib/python3.9/site-packages but not work command line

`python3 -m pip install --upgrade git+https://github.com/back-to/liveproxy.git`

this doesn't work because there is no **pip**

something is missing right now but what can you help me?

**Comment by thawtes** [comment]
i added /usr/bin/liveproxy

`
import re
import sys

from liveproxy.main import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())`

and work thanks
