### ISSUE TITLE
Using vlc instead of streamlink ?

### ISSUE THREAD

**Issue by BluchipStudio** [back-to/liveproxy#32]
Hi i have an mpd that is number based when i open the mpd directly in vls it plays perfectly fine but when i open it using streamlink it returns content from the past because segments are cached for 24 hours i can only assume streamlink is calculating the number wrong for the mpd representation 

i know vlc via command line allows for output to stdout so would it be possible to update this application to use vlc as a play option as well as streamlink and yt-dl ?

**Comment by back-to** [comment]
> but when i open it using streamlink it returns content from the past because segments are cached for 24 hours

if it is an issue with streamlink, report it there
https://github.com/streamlink/streamlink/issues/new/choose

> i know vlc via command line allows for output to stdout

share an example

**Comment by BluchipStudio** [comment]
I know for sure its an issue with streamlink but its more todo with the way the mpd is is layed out

what i would like to know is would it be possible to add vlc as a program for usage by this software as i assume it may take streamlink sometime to fix the issue if even ever but i know for sure vlc works perfect so if possible to use that then it fixies the issue right away and expands the script to work with more systems and provides more options

standard vlc output is just like streamlink and youtube-dl

vlc {INPUT} --sout="#std{mux=mp4,access=file,dst=-}"
