### ISSUE TITLE
Streams stop instantly

### ISSUE THREAD

**Issue by BluchipStudio** [back-to/liveproxy#34]
Ok so i am using this on a custom project to convert my signals from a few of my recivers into stream supported for web streaming via my own custom web player

I  have a cheap pc converted into a ubuntu server that has live proxy on it when i open ssh i can start liveproxy and everything runs as normal but the moment i close the ssh session the proxy stops

to save my self constantly having to login to ssh to start and stop the proxy i have decided to add a buttoninto my web player using jquery and php to handel starting the proxy using exec in php the proxy seems to start fine shows as active in terminal and outputs fine to the log file i have set 

but when i start a stream it says its starting then instantly stops and thats the end of that as its a local server i do have streamproxy running as root so i dont see it being a permissions issue.

when i enable debug loggin it dosent really print out much more information than

`[server.8b82f][INFO] User-Agent: VLC/3.0.16 LibVLC/3.0.16
[server.8b82f][INFO] Client: ('00.00.000.000', 55836)
[server.8b82f][INFO] Address: 00.00.000.000
[server.8b82f][DEBUG] Video-Software: /usr/local/bin/streamlink
[server.8b82f][DEBUG] ['streamlink', 'http://localhost/device/tbsocta/1f7b8a15201545c6a10d5b50db', 'best', '--stdout', '--loglevel', 'none']
[server.8b82f][INFO] Stream started 8b82f
[server.8b82f][DEBUG] Traceback (most recent call last):
[server.8b82f][DEBUG]   File "/usr/local/bin/streamlink", line 7, in <module>
[server.8b82f][INFO] Stream ended 8b82f
` 

as it works fine in ssh i am guessing its because it starting in php using exec so would it be possible to demon this project so itall ways runs in the background and then i dont need to try enable it this way

**Comment by back-to** [comment]
> [server.8b82f][DEBUG] Traceback (most recent call last):
[server.8b82f][DEBUG] File "/usr/local/bin/streamlink", line 7, in <module> 

seems broken, fix your streamlink install first

---

before you want to use any stream with liveproxy,
make sure it works with the streamlink command

when streamlink works, if needed you can debug streamlink with changing this none to debug
https://github.com/back-to/liveproxy/blob/master/liveproxy/server.py#L94=

---

> it be possible to demon this project so itall ways runs in the background

you can use `systemctl` and start a service for liveproxy on boot

**Comment by BluchipStudio** [comment]
> > [server.8b82f][DEBUG] Traceback (most recent call last):
> > [server.8b82f][DEBUG] File "/usr/local/bin/streamlink", line 7, in
> 
> seems broken, fix your streamlink install first
> 
> before you want to use any stream with liveproxy, make sure it works with the streamlink command
> 
> when streamlink works, if needed you can debug streamlink with changing this none to debug https://github.com/back-to/liveproxy/blob/master/liveproxy/server.py#L94=
> 
> > it be possible to demon this project so itall ways runs in the background
> 
> you can use `systemctl` and start a service for liveproxy on boot

I have edited this option and there are not a lot of other logs output streamlink plays the file fine on its own and plays fine when launched proxy via ssh on its own so its weird the issue only happens when launching from root using php i am using php because then i can start and stop it when needed as its a small local server i keep bare minimum working in the background unless i am using it

**Comment by back-to** [comment]
> only happens when launching from root using php

don't use root or php,
not much i can help you with.

**Comment by BluchipStudio** [comment]
> > only happens when launching from root using php
> 
> don't use root or php, not much i can help you with.

tried creating a service file to run at system boot following this guide 

https://www.howtogeek.com/687970/how-to-run-a-linux-program-at-startup-with-systemd/

and the liveproxy starts but again nothing plays when started this way as well
