### ISSUE TITLE
Simple Web UI with URL drop field for headless server?

### ISSUE THREAD

**Issue by WolfganP** [back-to/liveproxy#36]
Hi, FOA, thanks a lot for this amazing complement to streamlink.
The addition of the CMD interface is amazing as it simplifies liveproxy a lot for using it remotely (ie browsing for sites on a client, and then launching liveproxy/streamlink without having to convert to base64).

Going one step further in simplify this use case, would it be possible to implement a mini/simple web UI with a drop field to just paste the desired URL for liveproxy to launch it with some predetermined params? (ie. in my headless case --player-external-http params)

Thanks again.

**Comment by back-to** [comment]
Not sure what you want,
but `--player-external-http` makes no sense with **liveproxy**, it is the same feature.

If you want a shortcut, use streamlink config files.

https://streamlink.github.io/latest/cli.html#cmdoption-config
https://streamlink.github.io/latest/cli/config.html#configuration-file
https://streamlink.github.io/latest/cli/config.html#plugin-specific-configuration-file

---

`Simple Web UI`
This is **out of scope**
