### ISSUE TITLE
Broadcast same live stream to multiple clients

### ISSUE THREAD

**Issue by jlbribeiro** [back-to/liveproxy#39]
Hi @back-to,
First of all, thank you for `liveproxy`, been using it recently, quite a clever approach to the problem!

Since `liveproxy` targets _live streams_, I thought it would be a good enhancement to re-use the same command output for multiple clients, instead of opening multiple connections to the same upstream. Although I understand it might make the implementation a little bit more complex, I think it might make sense for use cases where you don't have something like TVHeadend consuming `liveproxy`'s stream (and broadcasting it).

What do you think?

Again, thank you for this project and idea!

**Comment by back-to** [comment]
> What do you think?

not the goal of this project,

there are already software which can do it.
