### ISSUE TITLE
More details in logs

### ISSUE THREAD

**Issue by mathieuthibault** [back-to/liveproxy#40]
Hello,

Is that possible to get more details in liveproxy's logs (when using "service liveproxy status" command for example) ? I would need to know which URLs have been opened using liveproxy.

Currently, we only have these infos :

févr. 22 05:56:12 SERVER IP liveproxy.sh[484]: [server.5a06c][INFO] User-Agent: CLIENT_USERAGENT
févr. 22 05:56:12 SERVER IP liveproxy.sh[484]: [server.5a06c][INFO] Client: ('CLIENT_IP', 38294)
févr. 22 05:56:12 SERVER IP liveproxy.sh[484]: [server.5a06c][INFO] Address: CLIENT_IP
févr. 22 05:56:12 SERVER IP liveproxy.sh[484]: [server.5a06c][INFO] Stream started xxxx
févr. 22 05:56:14 SERVER IP liveproxy.sh[484]: [server.5a06c][INFO] Stream ended xxxx

Is it possible to know which URL was opened by the client (http://SERVER_IP:53422/cmd/streamlink%20__URL__%20__PARAMETERS__) ?

Thanks!

**Comment by back-to** [comment]
start liveproxy with `liveproxy --loglevel DEBUG`
you can view the command used to start a stream

`[server.12345][DEBUG] ['streamlink', 'URL', 'best', '--stdout', '--loglevel', 'none']`
