### ISSUE TITLE
"Video-Software is not supported" in Alpine container

### ISSUE THREAD

**Issue by skanbg** [back-to/liveproxy#41]
Trying to create a Docker container that can handle requests with all tools (yt-dlp, streamlink, youtube-dl) supported by liveproxy

```dockerfile
FROM python:alpine3.18 AS release

WORKDIR /

RUN apk update
RUN apk upgrade
RUN apk add --no-cache ffmpeg

RUN python3 -m pip install --upgrade liveproxy
RUN python3 -m pip install -U yt-dlp
RUN python3 -m pip install -U streamlink

EXPOSE 53422

CMD ["liveproxy", "--host", "0.0.0.0", "--loglevel", "DEBUG"]
```

performing the request `http://127.0.0.1:53422/base64/eXQtZGxwIGh0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3VzZXIvZnJhbmNlMjQvbGl2ZQ==/` as stated in the README.md i am getting:
```
2023-05-18 23:00:23 [server.683d7][INFO] User-Agent: VLC/3.0.18 LibVLC/3.0.18
2023-05-18 23:00:23 [server.683d7][INFO] Client: ('172.20.0.1', 38844)
2023-05-18 23:00:23 [server.683d7][INFO] Address: 172.20.0.1
2023-05-18 23:00:23 [server.683d7][DEBUG] Video-Software: /usr/local/bin/yt-dlp
2023-05-18 23:00:23 [server.683d7][ERROR] Video-Software is not supported.
```

Traced the error to [this line](https://github.com/back-to/liveproxy/blob/35cad27645a0f0a078e6b802218c954bffb69642/liveproxy/server.py#L93) which should be caused if you provide invalid command encoded in base64 where the [regex checks](https://github.com/back-to/liveproxy/blob/35cad27645a0f0a078e6b802218c954bffb69642/liveproxy/server.py#L28) if yt-dlp, streamlink, youtube-dl is contained in the command fails.

Python is not part of my toolbox to trace/debug further, but [checked the regex online](https://regex101.com/r/qzULhE/1) if its caused by my Dockerfile setup. It seems to be working on the online regex site

**Comment by JunioCalu** [comment]
this solves for me: sudo -H python3 -m pip install --upgrade git+https://github.com/back-to/liveproxy.git
