### ISSUE TITLE
CElementTree causes exception when used in plugin

### ISSUE THREAD

**Issue by jairoxyz** [back-to/liveproxy#5]
Hi @back-to, this is the same bug I was trying to explain here https://github.com/streamlink/streamlink/issues/2366.

I am able to reproduce the behaviour on a clean Leia 18.1 install and with your script.module.streamlink v 1.0.0 installed from your repo. When trying to call a plugin that parses XML with ElementTree, it breaks when calling the compiled version CElelementTree in utils\__init__.py.

The detailed error with url http://www.rtve.es/directo/canal-24h is:

```
DEBUG: Traceback (most recent call last):
DEBUG:   File "\plugin.video.sltester\test.py", line 51, in PLAY
DEBUG:     streams = plugin.streams()
DEBUG:   File "\script.module.streamlink\resources\lib\streamlink\plugin\plugin.py", line 323, in streams
DEBUG:     ostreams = list(ostreams)
DEBUG:   File "\script.module.streamlink\resources\lib\streamlink\plugins\rtve.py", line 142, in _get_streams
DEBUG:     stream_data = self.zclient.get_cdn_list(content_id, schema=self.cdn_schema)
DEBUG:   File "\script.module.streamlink\resources\lib\streamlink\plugins\rtve.py", line 50, in get_cdn_list
DEBUG:     return schema.validate(data)
DEBUG:   File "\script.module.streamlink\resources\lib\streamlink\plugin\api\validate.py", line 482, in validate
DEBUG:     return validate(self.schema, value)
DEBUG:   File "\script.module.singledispatch\lib\singledispatch.py", line 210, in wrapper
DEBUG:     return dispatch(args[0].__class__)(*args, **kw)
DEBUG:   File "\script.module.streamlink\resources\lib\streamlink\plugin\api\validate.py", line 334, in validate_all
DEBUG:     value = validate(schema, value)
DEBUG:   File "\script.module.singledispatch\lib\singledispatch.py", line 210, in wrapper
DEBUG:     return dispatch(args[0].__class__)(*args, **kw)
DEBUG:   File "\script.module.streamlink\resources\lib\streamlink\plugin\api\validate.py", line 342, in validate_transform
DEBUG:     return schema.func(value)
DEBUG:   File "\script.module.streamlink\resources\lib\streamlink\utils\__init__.py", line 100, in parse_xml
DEBUG:     raise exception("Unable to parse {0}: {1} ({2})".format(name, err, snippet))
DEBUG: PluginError: Unable to parse XML: 'NoneType' object is not callable ("<?xml version='1.0'?><quality><pre ...)
DEBUG: [StreamLink] An error occured: Unable to parse XML: 'NoneType' object is not callable ("<?xml version='1.0'?><quality><pre ...)
```

When commenting out the compiled library all is fine. And it seems this problem has been around for some time: https://forum.kodi.tv/showthread.php?tid=185315.

I made a small addon for testing: [SL RTVE Plugin tester](https://github.com/jairoxyz/junk/blob/master/plugin.video.sltester.zip?raw=true)

Thanks in advance for checking.

Jx-

**Comment by back-to** [comment]
https://github.com/python/cpython/blob/3.7/Lib/xml/etree/cElementTree.py

`cElementTree` seems like just an alias, this might be broken on Windows.

if you want you can create a PR with removing it completely

https://github.com/streamlink/streamlink/search?q=cElementTree&unscoped_q=cElementTree

but this here is the wrong issue tracker.
