### ISSUE TITLE
Suggestion: Server the m3u from liveproxy

### ISSUE THREAD

**Issue by mjimeneznet** [back-to/liveproxy#6]
Hello, this is a suggestion.

In addition to the creation of the m3u file by passing the option --file why not add the option to serve the list from the liveproxy itself.

Example:
Current behaviour: `liveproxy --file example.m3u`
This generates a example.m3u.new with all the magic :) But I have to manually copy this file somewhere

Desired behaviour. Appart from the default, something like:
`liveproxy --file example.m3u --output http`
So you can have the list in a endpoint like:
`http://0.0.0.0:12345/example.m3u`

You can use liveproxy either acting as a proxy aswell as serving the m3u file.

Maybe a clean way to organise that:
`liveproxy --file example.m3u --output example.m3u.new` (writes to disk, like it does now)
`liveproxy --file example.m3u --output http` (serves the list from liveproxy)

Regards!

**Comment by back-to** [comment]
> --output example.m3u.new (writes to disk, like it does now)

I will add a command where you can change the output file

`liveproxy --file example.m3u --file-output my_file.m3u`

---

> --output http (serves the list from liveproxy)

it would take to much time to implement it correctly (auto-sync, anti-spam etc.)
not really worth it.

---

you can also use `curl` to automate some uploading to a sftp server

https://curl.haxx.se/docs/manual.html
